# GitHub branch protection rules for production
branch_protection_rules:
  - pattern: "main"
    required_status_checks:
      strict: true
      contexts:
        - "Build and Push"
    required_pull_request_reviews:
      required_approving_review_count: 1 # Require at least one approval change it 2 later
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    enforce_admins: false
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false
